defmodule Long.Copy do
  @moduledoc """
  Central catalog of bot/system copy ("话术") with i18n.

  One place defines every phrase, with per-locale built-in defaults. An
  operator can override any phrase per locale at runtime via
  `Long.Agent.Phrase` (edited in `/manage → Phrases`); overrides win.

  `t/3` resolves in this order, then interpolates `%{name}` placeholders
  from `bindings`:

      DB override (key, locale) → built-in (key, locale)
        → built-in (key, default_locale) → the key itself

  The default locale is `config :long, :default_locale` (defaults `"en"`).
  Pass a `locale` to `t/3` to render in a specific language (e.g. resolved
  from the chat user's `language_code`).
  """

  alias Long.Agent

  @default_locale "en"
  @locales ["en", "zh"]
  @pt_key {__MODULE__, :overrides}

  # The operator default locale is a `Long.Agent.Setting` (key below), cached
  # in persistent_term separately from the catalog overrides because it's read
  # on every `t/3`. Mirrors how `user_timezone` is stored — a setting, not a
  # memory/catalog row the LLM can touch.
  @default_locale_key "default_locale"
  @dl_pt_key {__MODULE__, :default_locale}

  # ── The catalog — the single source of truth for system copy ─────────
  @catalog %{
    "bots.cleared" => %{
      en: "Cleared this conversation's history, summary, checkpoint, and session memory. You can start fresh.",
      zh: "已清空这条会话的历史、摘要、检查点和 session 记忆。可以重新开始了。"
    },
    "bots.btw_ack" => %{
      en: "Got it — added that to the running task's context.",
      zh: "好的,已经加入到当前任务的上下文里。"
    },
    "bots.enqueued_ack" => %{
      en: "Got it — still finishing the previous message; I'll handle yours right after.",
      zh: "收到,前一条还在处理中,跑完后立刻处理你这条。"
    },
    "bots.bind_usage" => %{
      en: "Usage: /bind <code>. The code is generated by the group admin on the /manage members page.",
      zh: "用法:/bind <绑定码>。绑定码由组管理员在 /manage 的成员页面生成。"
    },
    "bots.bind_invalid" => %{
      en: "That bind code is invalid or expired — check with the group admin.",
      zh: "绑定码无效或已失效,请向组管理员确认。"
    },
    "bots.bind_ok" => %{
      en: "Linked this account to member “%{member}” in “%{group}”.",
      zh: "已把当前账号绑定到「%{group}」的成员「%{member}」。"
    },
    "bots.bind_failed" => %{
      en: "Binding failed, please try again.",
      zh: "绑定失败,请稍后重试。"
    },
    "bots.error" => %{
      en: "Something went wrong: %{reason}",
      zh: "出错了:%{reason}"
    },
    "status.idle" => %{
      en: "Idle — nothing running.",
      zh: "空闲,没有任务在跑。"
    },
    "status.idle_queue" => %{
      en: "Idle, but %{queue} queued message(s) and %{btw} note(s) pending. (unusual — a watcher should pick up immediately)",
      zh: "空闲,但还有 %{queue} 条排队消息和 %{btw} 条补充。(异常状态,通常 watcher 会立刻接力)"
    },
    "status.queued" => %{en: "%{n} queued", zh: "排队中 %{n} 条"},
    "status.notes" => %{en: "%{n} note(s)", zh: "补充 %{n} 条"},
    "status.on_request" => %{en: "on “%{request}” · ", zh: "处理「%{request}」 · "},
    "status.running" => %{en: "running %{duration}", zh: "运行中 %{duration}"},
    "status.turn" => %{en: " · turn %{turn}", zh: " · 第 %{turn} 轮"},
    "status.tool" => %{en: " · tool `%{tool}`", zh: " · 当前工具 `%{tool}`"},
    "status.turn_tool" => %{
      en: " · turn %{turn} · tool `%{tool}`",
      zh: " · 第 %{turn} 轮 · 当前工具 `%{tool}`"
    },
    "notify.envelope" => %{en: "📩 %{sender}:\n\n%{message}", zh: "📩 来自家人「%{sender}」:\n\n%{message}"},
    "notify.caller_unbound" => %{
      en: "this chat isn't linked to a group member yet — bind it first with `/bind <code>`.",
      zh: "当前会话还没有绑定组成员,先用 /bind <绑定码> 绑定后再试。"
    },
    "notify.no_others" => %{
      en: "you're the only member in this group — there's no one else to notify.",
      zh: "这个组里目前只有你一个人,没有其他成员可以通知。"
    },
    "notify.which_member" => %{
      en: "which member should I notify? options: %{options}.",
      zh: "想发给谁?可以发给:%{options}。"
    },
    "notify.no_match" => %{
      en: "no member matching “%{target}” — options: %{options}.",
      zh: "在组里没找到「%{target}」。可以发给:%{options}。"
    },
    "notify.ambiguous" => %{
      en: "several members match — say which: %{options}.",
      zh: "有多个成员符合,请指明发给谁:%{options}。"
    },
    "notify.no_channel" => %{
      en: "member “%{member}” has no linked chat account, so there's nothing to deliver to.",
      zh: "成员「%{member}」还没有绑定任何聊天账号,无法送达。"
    },
    "notify.delivered_none" => %{
      en: "couldn't deliver to “%{member}” — every channel failed (%{reason}).",
      zh: "没能把消息送达「%{member}」——所有渠道都失败了(%{reason})。"
    },
    "skill.owner_only" => %{
      en: "Only the group owner can create a shared skill.",
      zh: "只有组管理员能创建共享技能。"
    },
    "skill.caller_unbound" => %{
      en: "this chat isn't linked to a group member — bind it first with `/bind <code>`.",
      zh: "当前会话还没有绑定组成员,先用 /bind <绑定码> 绑定后再试。"
    },
    "skill.name_taken" => %{
      en: "a skill named “%{name}” already exists.",
      zh: "已存在名为「%{name}」的技能。"
    },
    "skill.create_failed" => %{
      en: "couldn't create the skill (%{reason}).",
      zh: "创建技能失败(%{reason})。"
    },
    "skill.not_found" => %{
      en: "no skill named “%{name}” that you can edit.",
      zh: "找不到你能编辑的、名为「%{name}」的技能。"
    },
    "skill.update_noop" => %{
      en: "nothing to update — provide a new description and/or body.",
      zh: "没有要更新的内容——请提供新的描述和/或正文。"
    },
    "skill.update_owner_only" => %{
      en: "Only the group owner can edit a shared skill.",
      zh: "只有组管理员能编辑共享技能。"
    },
    "skill.update_failed" => %{
      en: "couldn't update the skill (%{reason}).",
      zh: "更新技能失败(%{reason})。"
    },
    "tool.ask_default" => %{en: "Please provide input:", zh: "请提供输入:"},
    "tool.code_empty" => %{en: "[Status] ❌ failed: code is empty", zh: "[Status] ❌ 失败: code 为空"},
    "tool.file_no_content" => %{
      en: "[Status] ❌ failed: no content found",
      zh: "[Status] ❌ 失败: 未找到内容"
    },
    "chat.file_marker" => %{en: "[user sent a file: %{path}]", zh: "[用户发送文件: %{path}]"},
    "chat.error" => %{en: "⚠️ Something went wrong: %{reason}", zh: "⚠️ 出错了:%{reason}"}
  }

  @doc """
  The system-wide default locale: an operator override set in `/manage`,
  else `config :long, :default_locale`, else `"en"`.
  """
  def default_locale do
    default_locale_setting() || Application.get_env(:long, :default_locale, @default_locale)
  end

  @doc "The operator-set global default locale, or nil when unset (config fallback applies)."
  def default_locale_setting, do: cached_default_locale()

  @doc "Set the global default locale (blank/nil clears it). Persisted as a setting."
  def put_default_locale(locale) when is_binary(locale) and locale != "" do
    {:ok, _} = Agent.put_setting(%{key: @default_locale_key, value: locale})
    reload_default_locale()
    :ok
  end

  def put_default_locale(_) do
    case Agent.get_setting(@default_locale_key) do
      {:ok, row} -> Agent.delete_setting(row)
      _ -> :ok
    end

    reload_default_locale()
    :ok
  end

  @doc "Locales the catalog ships defaults for."
  def locales, do: @locales

  @doc "Every catalog key, sorted."
  def keys, do: @catalog |> Map.keys() |> Enum.sort()

  @doc "The built-in (un-overridden) default for `key` in `locale`, or nil."
  def builtin(key, locale) when is_binary(key) and is_binary(locale),
    do: get_in(@catalog, [key, locale_atom(locale)])

  @doc """
  Resolve a phrase. `locale` defaults to `default_locale/0`. `bindings`
  fill `%{name}` placeholders.
  """
  @spec t(String.t(), map(), String.t() | nil) :: String.t()
  def t(key, bindings \\ %{}, locale \\ nil) when is_binary(key) do
    locale = normalize_locale(locale || default_locale())

    template =
      override(key, locale) ||
        builtin(key, locale) ||
        builtin(key, @default_locale) ||
        key

    interpolate(template, bindings)
  end

  @doc "Reload DB overrides into the cache. Call after editing a `Phrase`."
  def reload, do: do_reload() && :ok

  # ── overrides cache (persistent_term, lazily loaded) ─────────────────

  defp override(key, locale), do: Map.get(overrides(), {key, locale})

  defp overrides do
    case :persistent_term.get(@pt_key, :unset) do
      :unset -> do_reload()
      map -> map
    end
  end

  defp do_reload do
    map =
      case Agent.list_phrases() do
        {:ok, rows} ->
          for r <- rows, is_binary(r.text) and r.text != "", into: %{} do
            {{r.key, normalize_locale(r.locale)}, r.text}
          end

        _ ->
          %{}
      end

    :persistent_term.put(@pt_key, map)
    map
  end

  # The operator default locale, cached separately from catalog overrides
  # since it's read on every t/3.
  defp cached_default_locale do
    case :persistent_term.get(@dl_pt_key, :unset) do
      :unset -> reload_default_locale()
      val -> val
    end
  end

  defp reload_default_locale do
    val =
      case Agent.get_setting(@default_locale_key) do
        {:ok, %{value: v}} when is_binary(v) and v != "" -> v
        _ -> nil
      end

    :persistent_term.put(@dl_pt_key, val)
    val
  end

  # ── helpers ──────────────────────────────────────────────────────────

  defp interpolate(template, bindings) when bindings == %{}, do: template

  defp interpolate(template, bindings) do
    Enum.reduce(bindings, template, fn {k, v}, acc ->
      String.replace(acc, "%{#{k}}", to_string(v))
    end)
  end

  # "zh-Hans" / "zh_CN" → "zh"; "en-US" → "en". Unknown locales pass
  # through as-is — `t/3` then falls back to the default via `builtin/2`,
  # and override rows stay keyed under their own locale.
  defp normalize_locale(locale) when is_binary(locale),
    do: locale |> String.downcase() |> String.split(["-", "_"]) |> hd()

  defp normalize_locale(_), do: @default_locale

  defp locale_atom("en"), do: :en
  defp locale_atom("zh"), do: :zh
  defp locale_atom(_), do: nil
end
