defmodule LongWeb.GraphqlSchema do
  @moduledoc """
  Absinthe schema that exposes Long's Ash resources to the AI (and the
  web UI / external clients) over GraphQL. The actual types, queries,
  and mutations are generated by `AshGraphql` from the `graphql` blocks
  inside each resource — this module just wires the domain in.

  Endpoint mounted at `/graphql` (router.ex). Introspection lets the
  agent ask `{ __schema { queryType { fields { name } } } }` to learn
  what it can do without us maintaining a separate cheatsheet.
  """

  use Absinthe.Schema

  use AshGraphql,
    domains: [Long.Agent]

  query do
    # AshGraphql injects the generated queries into this block.
  end

  mutation do
    # AshGraphql injects the generated mutations here.
  end
end
