import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :long, LongWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# `force_ssl` is intentionally NOT enabled — Long is meant to be
# self-hosted on a LAN / via SSH tunnel, where TLS is provided by a
# reverse proxy (caddy / nginx / Cloudflare Tunnel) if at all.
# Hardcoding `force_ssl` here would 301 every plain HTTP request to
# `https://<PHX_HOST>`, breaking access from another machine on the
# same network without a cert.
#
# To re-enable when fronted by a reverse proxy that terminates TLS:
#
#     config :long, LongWeb.Endpoint,
#       force_ssl: [rewrite_on: [:x_forwarded_proto]]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
