defmodule Long.Repo.Migrations.AddLlmProviderDefault do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:agent_llm_configs) do
      add :provider, :text
      add :wire_protocol, :text
      add :default, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:agent_llm_configs) do
      remove :default
      remove :wire_protocol
      remove :provider
    end
  end
end