defmodule Long.Repo.Migrations.AddMonitors do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:agent_monitors, primary_key: false) do
      add :session_id,
          references(:agent_sessions,
            column: :id,
            name: "agent_monitors_session_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :metadata, :map, default: %{}
      add :last_digest, :text
      add :last_output, :map, default: %{}
      add :last_status, :text
      add :last_notified_at, :utc_datetime
      add :next_run_at, :utc_datetime
      add :last_run_at, :utc_datetime
      add :secret_name, :text
      add :enabled, :boolean, null: false
      add :cooldown_minutes, :bigint
      add :max_delay_hours, :bigint
      add :every_n, :bigint
      add :schedule_time, :text
      add :repeat, :text, null: false
      add :language, :text
      add :script, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:agent_monitors, [:name], name: "agent_monitors_name_index")
  end

  def down do
    drop_if_exists unique_index(:agent_monitors, [:name], name: "agent_monitors_name_index")

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `agent_monitors` table without the `agent_monitors_session_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:agent_monitors)
  end
end