defmodule Long.Repo.Migrations.AddSessionSummaryThrough do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:agent_sessions) do
      add :summary_through_inserted_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:agent_sessions) do
      remove :summary_through_inserted_at
    end
  end
end