defmodule Long.Repo.Migrations.AddApiKeyField do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:agent_llm_configs) do
      add :api_key, :text
    end
  end

  def down do
    alter table(:agent_llm_configs) do
      remove :api_key
    end
  end
end