defmodule Long.Repo.Migrations.AddPhrases do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:agent_phrases, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :text, :text
      add :locale, :text, null: false
      add :key, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:agent_phrases, [:key, :locale], name: "agent_phrases_key_locale_index")
  end

  def down do
    drop_if_exists unique_index(:agent_phrases, [:key, :locale],
                     name: "agent_phrases_key_locale_index"
                   )

    drop table(:agent_phrases)
  end
end