defmodule Long.Repo.Migrations.AddBotUserCredentialName do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:agent_bot_users) do
      add :credential_name, :text
    end
  end

  def down do
    alter table(:agent_bot_users) do
      remove :credential_name
    end
  end
end