defmodule Long.Repo.Migrations.AddHouseholdAndMembers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:agent_households, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:agent_household_members, primary_key: false) do
      add :household_id,
          references(:agent_households,
            column: :id,
            name: "agent_household_members_household_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :bind_code, :text
      add :role, :text, null: false
      add :relation, :text, null: false
      add :display_name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:agent_household_members, [:bind_code],
             name: "agent_household_members_unique_bind_code_index"
           )

    alter table(:agent_bot_users) do
      add :member_id,
          references(:agent_household_members,
            column: :id,
            name: "agent_bot_users_member_id_fkey",
            type: :uuid,
            on_delete: :nilify_all
          )
    end
  end

  def down do
    alter table(:agent_bot_users) do
      remove :member_id
    end

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `agent_bot_users` table without the `agent_bot_users_member_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop_if_exists unique_index(:agent_household_members, [:bind_code],
                     name: "agent_household_members_unique_bind_code_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `agent_household_members` table without the `agent_household_members_household_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:agent_household_members)

    drop table(:agent_households)
  end
end