defmodule Long.Repo.Migrations.AddMonitorRunIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:agent_monitor_runs, ["monitor_id", "inserted_at"])
  end

  def down do
    drop_if_exists index(:agent_monitor_runs, ["monitor_id", "inserted_at"],
                     name: "agent_monitor_runs_monitor_id_inserted_at_index"
                   )
  end
end