defmodule Long.Repo.Migrations.AddTurnSnapshots do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:agent_turn_snapshots, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :llm_alias, :text
      add :last_assistant_text, :text
      add :tool_results_json, :text
      add :pending_tool_calls_json, :text
      add :messages_json, :text
      add :stage, :text, null: false
      add :turn, :bigint, null: false
      add :session_id, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:agent_turn_snapshots, [:session_id],
             name: "agent_turn_snapshots_session_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:agent_turn_snapshots, [:session_id],
                     name: "agent_turn_snapshots_session_id_index"
                   )

    drop table(:agent_turn_snapshots)
  end
end