defmodule Long.Repo.Migrations.AddWechatCredentials do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:agent_wechat_credentials, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :updates_buf, :text
      add :ilink_bot_id, :text
      add :bot_token, :text
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:agent_wechat_credentials, [:name],
             name: "agent_wechat_credentials_name_index"
           )
  end

  def down do
    drop_if_exists unique_index(:agent_wechat_credentials, [:name],
                     name: "agent_wechat_credentials_name_index"
                   )

    drop table(:agent_wechat_credentials)
  end
end