defmodule Long.Repo.Migrations.AddMonitorRuns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:agent_monitor_runs, primary_key: false) do
      add :monitor_id,
          references(:agent_monitors,
            column: :id,
            name: "agent_monitor_runs_monitor_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :ran_at, :utc_datetime
      add :stdout_tail, :text
      add :message, :text
      add :decision, :text
      add :status, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `agent_monitor_runs` table without the `agent_monitor_runs_monitor_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:agent_monitor_runs)
  end
end