defmodule Long.Repo.Migrations.AddSilentReflection do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # `default: false` is required so `ADD COLUMN ... NOT NULL` succeeds on
    # tables that already have rows (and keeps existing rows loud/visible).
    alter table(:agent_turn_snapshots) do
      add :reflection?, :boolean, null: false, default: false
    end

    alter table(:agent_scheduled_tasks) do
      add :silent, :boolean, null: false, default: false
    end

    alter table(:agent_messages) do
      add :internal, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:agent_messages) do
      remove :internal
    end

    alter table(:agent_scheduled_tasks) do
      remove :silent
    end

    alter table(:agent_turn_snapshots) do
      remove :reflection?
    end
  end
end