defmodule Long.Repo.Migrations.AddMemoryKindImportanceUsage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:agent_session_memories, primary_key: false) do
      add :session_id,
          references(:agent_sessions,
            column: :id,
            name: "agent_session_memories_session_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :last_used_at, :utc_datetime_usec
      add :hit_count, :bigint, null: false
      add :importance, :bigint, null: false
      add :kind, :text, null: false
      add :value, :text, null: false
      add :key, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:agent_session_memories, [:session_id, :key],
             name: "agent_session_memories_session_key_index"
           )

    # SQLite can't ADD COLUMN NOT NULL without a default — existing
    # rows wouldn't satisfy. Defaults mirror the resource attributes.
    alter table(:agent_global_memory) do
      add :kind, :text, null: false, default: "fact"
      add :importance, :bigint, null: false, default: 3
      add :hit_count, :bigint, null: false, default: 0
      add :last_used_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:agent_global_memory) do
      remove :last_used_at
      remove :hit_count
      remove :importance
      remove :kind
    end

    drop_if_exists unique_index(:agent_session_memories, [:session_id, :key],
                     name: "agent_session_memories_session_key_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `agent_session_memories` table without the `agent_session_memories_session_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:agent_session_memories)
  end
end