defmodule Long.Repo.Migrations.AddSecrets do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:agent_secrets, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :description, :text
      add :value, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:agent_secrets, [:name], name: "agent_secrets_name_index")
  end

  def down do
    drop_if_exists unique_index(:agent_secrets, [:name], name: "agent_secrets_name_index")

    drop table(:agent_secrets)
  end
end