defmodule Long.Repo.Migrations.Phase0AgentSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:agent_working_checkpoints, primary_key: false) do
      add :session_id,
          references(:agent_sessions,
            column: :id,
            name: "agent_working_checkpoints_session_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :key_info, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:agent_skills, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :use_count, :bigint, null: false
      add :last_used_at, :utc_datetime
      add :tags, {:array, :text}, default: []
      add :description, :text
      add :sop_path, :text
      add :relative_path, :text, null: false
      add :kind, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:agent_skills, [:name], name: "agent_skills_name_index")

    create table(:agent_sessions, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :ended_at, :utc_datetime
      add :token_usage, :bigint, null: false
      add :summary, :text
      add :llm_alias, :text
      add :status, :text, null: false
      add :title, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:agent_working_checkpoints, [:session_id],
             name: "agent_working_checkpoints_session_id_index"
           )

    create table(:agent_session_archives, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :archived_at, :utc_datetime, null: false
      add :payload, :map
      add :insights, :text
      add :summary, :text
      add :title, :text
      add :original_session_id, :uuid
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:agent_messages, primary_key: false) do
      add :session_id,
          references(:agent_sessions,
            column: :id,
            name: "agent_messages_session_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :turn, :bigint, null: false
      add :tool_results, {:array, :map}, default: []
      add :tool_calls, {:array, :map}, default: []
      add :blocks, :map
      add :content, :text
      add :role, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:agent_llm_configs, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :sort_order, :bigint, null: false
      add :enabled, :boolean, null: false
      add :params, :map, default: %{}
      add :api_key_env_var, :text
      add :api_base, :text
      add :model, :text
      add :kind, :text, null: false
      add :alias, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:agent_llm_configs, [:alias], name: "agent_llm_configs_alias_index")

    create table(:agent_global_memory, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :value, :text, null: false
      add :key, :text, null: false
      add :scope, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:agent_global_memory, [:scope, :key],
             name: "agent_global_memory_scope_key_index"
           )
  end

  def down do
    drop_if_exists unique_index(:agent_global_memory, [:scope, :key],
                     name: "agent_global_memory_scope_key_index"
                   )

    drop table(:agent_global_memory)

    drop_if_exists unique_index(:agent_llm_configs, [:alias],
                     name: "agent_llm_configs_alias_index"
                   )

    drop table(:agent_llm_configs)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `agent_messages` table without the `agent_messages_session_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:agent_messages)

    drop table(:agent_session_archives)

    drop_if_exists unique_index(:agent_working_checkpoints, [:session_id],
                     name: "agent_working_checkpoints_session_id_index"
                   )

    drop table(:agent_sessions)

    drop_if_exists unique_index(:agent_skills, [:name], name: "agent_skills_name_index")

    drop table(:agent_skills)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `agent_working_checkpoints` table without the `agent_working_checkpoints_session_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:agent_working_checkpoints)
  end
end