defmodule Long.Repo.Migrations.AddSessionTitleLocked do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:agent_sessions) do
      add :title_locked, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:agent_sessions) do
      remove :title_locked
    end
  end
end