defmodule Long.Repo.Migrations.SearchConfig do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:agent_search_configs, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :sort_order, :bigint, null: false
      add :enabled, :boolean, null: false
      add :params, :map, default: %{}
      add :api_key_env_var, :text
      add :api_key, :text
      add :provider, :text, null: false
      add :alias, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:agent_search_configs, [:alias], name: "agent_search_configs_alias_index")
  end

  def down do
    drop_if_exists unique_index(:agent_search_configs, [:alias],
                     name: "agent_search_configs_alias_index"
                   )

    drop table(:agent_search_configs)
  end
end