defmodule Long.Repo.Migrations.AddTelegramCredentialMember do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:agent_telegram_credentials) do
      add :member_id,
          references(:agent_household_members,
            column: :id,
            name: "agent_telegram_credentials_member_id_fkey",
            type: :uuid,
            on_delete: :nilify_all
          )
    end
  end

  def down do
    alter table(:agent_telegram_credentials) do
      remove :member_id
    end

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `agent_telegram_credentials` table without the `agent_telegram_credentials_member_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."
  end
end