defmodule Long.Repo.Migrations.AddLocaleSettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:agent_wechat_credentials) do
      add :locale, :text
    end

    alter table(:agent_telegram_credentials) do
      add :locale, :text
    end

    alter table(:agent_households) do
      add :locale, :text
    end

    alter table(:agent_household_members) do
      add :locale, :text
    end
  end

  def down do
    alter table(:agent_household_members) do
      remove :locale
    end

    alter table(:agent_households) do
      remove :locale
    end

    alter table(:agent_telegram_credentials) do
      remove :locale
    end

    alter table(:agent_wechat_credentials) do
      remove :locale
    end
  end
end