defmodule Long.Repo.Migrations.Phase7BotUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:agent_bot_users, primary_key: false) do
      add :session_id,
          references(:agent_sessions,
            column: :id,
            name: "agent_bot_users_session_id_fkey",
            type: :uuid,
            on_delete: :nilify_all
          )

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :metadata, :map, default: %{}
      add :display_name, :text
      add :chat_id, :text
      add :external_id, :text, null: false
      add :platform, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:agent_bot_users, [:platform, :external_id],
             name: "agent_bot_users_platform_external_index"
           )
  end

  def down do
    drop_if_exists unique_index(:agent_bot_users, [:platform, :external_id],
                     name: "agent_bot_users_platform_external_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `agent_bot_users` table without the `agent_bot_users_session_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:agent_bot_users)
  end
end