defmodule Long.Agent.PythonEnv do
  @moduledoc """
  Owns the uv-managed Python project the agent runs code in.

  Layout (relative to the configured `:workspace_root`):

      <workspace>/
        pyproject.toml        # uv project manifest, AI can `uv add` into this
        .python-version       # uv-managed Python pin
        .venv/                # uv-managed venv
        <ai files…>           # transient scripts, outputs, etc.

  `ensure!/0` is idempotent: first call writes a minimal pyproject.toml if
  missing, subsequent calls noop. We deliberately do **not** call `uv init`
  — `uv init` would also drop a `main.py` template and a `README.md`,
  cluttering the agent's view. A 4-line pyproject is enough for `uv add`
  and `uv run` to work.
  """

  @minimum_pyproject """
  [project]
  name = "long-agent-workspace"
  version = "0.1.0"
  description = "Workspace where Long.Agent runs Python via uv."
  requires-python = ">=3.10"
  dependencies = []
  """

  @python_shim """
  #!/usr/bin/env bash
  # Auto-generated by Long.Agent.PythonEnv. Bare `python` / `python3` in
  # bash code_run resolves to this shim, which delegates to the uv-managed
  # venv. Lets AI write `python - <<'PY' … PY` heredocs without worrying
  # about uv.
  exec uv run --quiet --project "$(dirname "$0")" python "$@"
  """

  @doc """
  Path to the workspace root. Honors `config :long, Long.Agent,
  workspace_root: …` and falls back to the legacy `:temp_root` so existing
  setups keep working.
  """
  def root do
    cfg = Application.get_env(:long, Long.Agent, [])

    cfg[:workspace_root] ||
      cfg[:temp_root] ||
      Path.expand("priv/agent/workspace", File.cwd!())
  end

  @doc "Returns the path to the `uv` binary, or `{:error, :uv_missing}` if not on PATH."
  def uv_bin do
    case System.find_executable("uv") do
      nil -> {:error, :uv_missing}
      path -> {:ok, path}
    end
  end

  @doc """
  Make sure `<root>/pyproject.toml` + `<root>/python` + `<root>/python3`
  shims exist. Returns `{:ok, root}`. Idempotent; cheap to call repeatedly.

  The shims let bash code_run invocations use bare `python` / `python3`
  (very common in LLM-generated heredocs) and have them route through
  `uv run python` automatically.
  """
  def ensure!(root \\ nil) do
    root = root || root()
    File.mkdir_p!(root)

    manifest = Path.join(root, "pyproject.toml")
    unless File.exists?(manifest), do: File.write!(manifest, @minimum_pyproject)

    install_shim(Path.join(root, "python"))
    install_shim(Path.join(root, "python3"))

    {:ok, root}
  end

  # File.write + File.chmod are idempotent; skip the File.exists? race.
  defp install_shim(path) do
    File.write!(path, @python_shim)
    File.chmod!(path, 0o755)
  end
end
